# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: diarist
      POSTGRES_PASSWORD: journal
      POSTGRES_DB: diarist

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080